name: Build documentation

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - '**'

# TODO: only request needed permissions
permissions: write-all

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Install asciidoctor-reducer
        run: sudo gem install asciidoctor-reducer --pre

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Reduce documentation
        run: asciidoctor-reducer -o README.adoc docs/index.adoc

      - name: Commit documentation
        uses: EndBug/add-and-commit@v9
